name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init go.mk submodule
      run: git submodule update --init --recursive go.mk
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27
        args: --timeout 2m
    - name: Run tests
      run: make lint test-verbose test-acc
      env:
        EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
        EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init go.mk submodule
      run: git submodule update --init --recursive go.mk
    - name: Build
      run: make build
