name: CI

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init go.mk submodule
      run: git submodule update --init --recursive go.mk
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27
        args: --timeout 2m
    - name: Run tests
      run: env ; make lint test-verbose test-acc
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init go.mk submodule
      run: git submodule update --init --recursive go.mk
    - name: Build
      run: make build
